#ifndef GUARD_DEAFULTS_H
#define GUARD_DEFAULTS_H

#define SPECIES_DEFAULT SPECIES_BULBASAUR
#define ITEM_INDEX_DEFAULT ITEM_RARE_CANDY
#define EXPERIENCE_DEFAULT 1250000

//Moves specifer
#define MOVE1_INDEX_DEFAULT MOVE_HIDDEN_POWER
#define MOVE2_INDEX_DEFAULT MOVE_NONE
#define MOVE3_INDEX_DEFAULT MOVE_NONE
#define MOVE4_INDEX_DEFAULT MOVE_NONE

//Actual PP for the Moves
#define PP_MOVE1_DEFAULT 5
#define PP_MOVE2_DEFAULT 5
#define PP_MOVE3_DEFAULT 5
#define PP_MOVE4_DEFAULT 5

//PP Bonuses 
#define PP_BONUS_MOVE1_DEFAULT 3
#define PP_BONUS_MOVE2_DEFAULT 3
#define PP_BONUS_MOVE3_DEFAULT 3
#define PP_BONUS_MOVE4_DEFAULT 3

#define FRIENDSHIP 0xFF  //MAX Friendship, does not matter because of trade

//Contest Values
#define COOLNESS_DEFAULT 0
#define BEAUTY_DEFAULT 0
#define CUTENESS_DEFAULT 0
#define SMARTNESS_DEFAULT 0
#define TOUGHNESS_DEFAULT 0
#define FEEL_DEFAULT 0

//Effort Values
#define HP_EV_DEFAULT 0
#define ATTACK_EV_DEFAULT 0
#define DEFENSE_EV_DEFAULT 0
#define SPEED_EV_DEFAULT 0
#define SPEZ_ATTACK_EV_DEFAULT 0
#define SPEZ_DEFENSE_EV_DEFAULT 0

//Inherited Values
#define HP_IV_DEFAULT  31
#define ATTACK_IV_DEFAULT  31
#define DEFENSE_IV_DEFAULT  31
#define SPEED_IV_DEFAULT  31
#define SPEZ_ATTACK_IV_DEFAULT  31
#define SPEZ_DEFENSE_IV_DEFAULT  31

//Ribbons

#define COOL_RIBBON_DEFAULT 0
#define BEAUTY_RIBBON_DEFAULT 0
#define CUTE_RIBBON_DEFAULT 0
#define SMART_RIBBON_DEFAULT 0
#define TOUGH_RIBBON_DEFAULT 0
#define CHAMPION_RIBBON_DEFAULT 0
#define WINNING_RIBBON_DEFAULT 0
#define VICTORY_RIBBON_DEFAULT 0
#define ARTIST_RIBBON_DEFAULT 0
#define EFFORT_RIBBON_DEFAULT 0
#define SPECIAL1_RIBBON_DEFAULT 0
#define SPECIAL2_RIBBON_DEFAULT 0
#define SPECIAL3_RIBBON_DEFAULT 0
#define SPECIAL4_RIBBON_DEFAULT 0
#define SPECIAL5_RIBBON_DEFAULT 0
#define SPECIAL6_RIBBON_DEFAULT 0
#define PADDING_RIBBON_DEFAULT 0
#define OBEDIENCE_RIBBON_DEFAULT 0


#define MET_GAME_DEFAULT GAME_LEAFGREEN
#define POKEBALL_CAUGHT_DEFAULT POKEBALL_STANDARD
#define MET_LANGUAGE_DEFAULT LANGUAGE_GERMAN

#define MET_LOCATION_DEFAULT 0x58

#define MET_LEVEL_DEFAULT 0   //0 = EGG
#define LEVEL_DEFAULT 100


#define NATURE_DEFAULT 0

#define ABILITY_DEFAULT ABILITY_PRIMARY

#define SECRET_ID_LAMBO 0x06A6
#define SECRET_ID_KEVIN 0x392B

#define TRAINER_ID_LAMBO 0x4753
#define TRAINER_ID_KEVIN 0x8D44

#define SECRET_ID_DANIEL 0x60AC
#define OT_TRAINER_ID_DANIEL 0xC371
#define TRAINER_ID_DANIEL 0x60ACC371 //Leafgreen Daniel

#define SECRET_ID SECRET_ID_DANIEL
#define OT_TRAINER_ID OT_TRAINER_ID_DANIEL
//#define TRAINER_ID 0x06A64753

//#define TRAINER_ID 0x60ACC371 //Leafgreen Daniel
#define TRAINER_ID (SECRET_ID << 16) + OT_TRAINER_ID

#define TRAINER_NAME_DEFAULT "Daniel"
#define NICKNAME_DEFAULT "Pokemon"

#endif