# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/daniel/Masterthesis/GB_MASTER_UNIT/Own_Files/constraints/Zybo-Z7-Master.xdc

# Block Designs: bd/GB_UNIT_design/GB_UNIT_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GB_UNIT_design || ORIG_REF_NAME==GB_UNIT_design} -quiet] -quiet

# IP: bd/GB_UNIT_design/ip/GB_UNIT_design_processing_system7_0_0/GB_UNIT_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GB_UNIT_design_processing_system7_0_0 || ORIG_REF_NAME==GB_UNIT_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/GB_UNIT_design/ip/GB_UNIT_design_axi_bram_ctrl_0_0/GB_UNIT_design_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GB_UNIT_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==GB_UNIT_design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/GB_UNIT_design/ip/GB_UNIT_design_axi_smc_0/GB_UNIT_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GB_UNIT_design_axi_smc_0 || ORIG_REF_NAME==GB_UNIT_design_axi_smc_0} -quiet] -quiet

# IP: bd/GB_UNIT_design/ip/GB_UNIT_design_rst_ps7_0_50M_0/GB_UNIT_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GB_UNIT_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==GB_UNIT_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/GB_UNIT_design/ip/GB_UNIT_design_axi_gpio_0_0/GB_UNIT_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GB_UNIT_design_axi_gpio_0_0 || ORIG_REF_NAME==GB_UNIT_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/GB_UNIT_design/ip/GB_UNIT_design_axi_gpio_1_0/GB_UNIT_design_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GB_UNIT_design_axi_gpio_1_0 || ORIG_REF_NAME==GB_UNIT_design_axi_gpio_1_0} -quiet] -quiet

# XDC: /home/daniel/Masterthesis/GB_MASTER_UNIT/GB_MASTER_UNIT.gen/sources_1/bd/GB_UNIT_design/GB_UNIT_design_ooc.xdc
