#ifndef ITEM_HEADER
#define ITEM_HEADER
char item_string_file[][20] = {
"None",
"Master Ball",
"Ultra Ball",
"Great Ball",
"Poke Ball",
"Safari Ball",
"Net Ball",
"Dive Ball",
"Nest Ball",
"Repeat Ball",
"Timer Ball",
"Luxury Ball",
"Premier Ball",
"Potion",
"Antidote",
"Burn Heal",
"Ice Heal",
"Awakening",
"Paralyze Heal",
"Full Restore",
"Max Potion",
"Hyper Potion",
"Super Potion",
"Full Heal",
"Revive",
"Max Revive",
"Fresh Water",
"Soda Pop",
"Lemonade",
"Moomoo Milk",
"Energy Powder",
"Energy Root",
"Heal Powder",
"Revival Herb",
"Ether",
"Max Ether",
"Elixir",
"Max Elixir",
"Lava Cookie",
"Blue Flute",
"Yellow Flute",
"Red Flute",
"Black Flute",
"White Flute",
"Berry Juice",
"Sacred Ash",
"Shoal Salt",
"Shoal Shell",
"Red Shard",
"Blue Shard",
"Yellow Shard",
"Green Shard",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Hp Up",
"Protein",
"Iron",
"Carbos",
"Calcium",
"Rare Candy",
"Pp Up",
"Zinc",
"Pp Max",
"Unknown Item",
"Guard Spec",
"Dire Hit",
"X Attack",
"X Defend",
"X Speed",
"X Accuracy",
"X Special",
"Poke Doll",
"Fluffy Tail",
"Unknown Item",
"Super Repel",
"Max Repel",
"Escape Rope",
"Repel",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Sun Stone",
"Moon Stone",
"Fire Stone",
"Thunder Stone",
"Water Stone",
"Leaf Stone",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Tiny Mushroom",
"Big Mushroom",
"Unknown Item",
"Pearl",
"Big Pearl",
"Stardust",
"Star Piece",
"Nugget",
"Heart Scale",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Orange Mail",
"Harbor Mail",
"Glitter Mail",
"Mech Mail",
"Wood Mail",
"Wave Mail",
"Bead Mail",
"Shadow Mail",
"Tropic Mail",
"Dream Mail",
"Fab Mail",
"Retro Mail",
"Cheri Berry",
"Chesto Berry",
"Pecha Berry",
"Rawst Berry",
"Aspear Berry",
"Leppa Berry",
"Oran Berry",
"Persim Berry",
"Lum Berry",
"Sitrus Berry",
"Figy Berry",
"Wiki Berry",
"Mago Berry",
"Aguav Berry",
"Iapapa Berry",
"Razz Berry",
"Bluk Berry",
"Nanab Berry",
"Wepear Berry",
"Pinap Berry",
"Pomeg Berry",
"Kelpsy Berry",
"Qualot Berry",
"Hondew Berry",
"Grepa Berry",
"Tamato Berry",
"Cornn Berry",
"Magost Berry",
"Rabuta Berry",
"Nomel Berry",
"Spelon Berry",
"Pamtre Berry",
"Watmel Berry",
"Durin Berry",
"Belue Berry",
"Liechi Berry",
"Ganlon Berry",
"Salac Berry",
"Petaya Berry",
"Apicot Berry",
"Lansat Berry",
"Starf Berry",
"Enigma Berry",
"Unused Berry 1",
"Unused Berry 2",
"Unused Berry 3",
"Bright Powder",
"White Herb",
"Macho Brace",
"Exp Share",
"Quick Claw",
"Soothe Bell",
"Mental Herb",
"Choice Band",
"Kings Rock",
"Silver Powder",
"Amulet Coin",
"Cleanse Tag",
"Soul Dew",
"Deep Sea Tooth",
"Deep Sea Scale",
"Smoke Ball",
"Everstone",
"Focus Band",
"Lucky Egg",
"Scope Lens",
"Metal Coat",
"Leftovers",
"Dragon Scale",
"Light Ball",
"Soft Sand",
"Hard Stone",
"Miracle Seed",
"Black Glasses",
"Black Belt",
"Magnet",
"Mystic Water",
"Sharp Beak",
"Poison Barb",
"Never Melt Ice",
"Spell Tag",
"Twisted Spoon",
"Charcoal",
"Dragon Fang",
"Silk Scarf",
"Up Grade",
"Shell Bell",
"Sea Incense",
"Lax Incense",
"Lucky Punch",
"Metal Powder",
"Thick Club",
"Stick",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Unknown Item",
"Red Scarf",
"Blue Scarf",
"Pink Scarf",
"Green Scarf",
"Yellow Scarf",
"Mach Bike",
"Coin Case",
"Itemfinder",
"Old Rod",
"Good Rod",
"Super Rod",
"Ss Ticket",
"Contest Pass",
"10b",
"Wailmer Pail",
"Devon Goods",
"Soot Sack",
"Basement Key",
"Acro Bike",
"Pokeblock Case",
"Letter",
"Eon Ticket",
"Red Orb",
"Blue Orb",
"Scanner",
"Go Goggles",
"Meteorite",
"Room 1 Key",
"Room 2 Key",
"Room 4 Key",
"Room 6 Key",
"Storage Key",
"Root Fossil",
"Claw Fossil",
"Devon Scope",
"Tm01 Focus Punch",
"Tm02 Dragon Claw",
"Tm03 Water Pulse",
"Tm04 Calm Mind",
"Tm05 Roar",
"Tm06 Toxic",
"Tm07 Hail",
"Tm08 Bulk Up",
"Tm09 Bullet Seed",
"Tm10 Hidden Power",
"Tm11 Sunny Day",
"Tm12 Taunt",
"Tm13 Ice Beam",
"Tm14 Blizzard",
"Tm15 Hyper Beam",
"Tm16 Light Screen",
"Tm17 Protect",
"Tm18 Rain Dance",
"Tm19 Giga Drain",
"Tm20 Safeguard",
"Tm21 Frustration",
"Tm22 Solar Beam",
"Tm23 Iron Tail",
"Tm24 Thunderbolt",
"Tm25 Thunder",
"Tm26 Earthquake",
"Tm27 Return",
"Tm28 Dig",
"Tm29 Psychic",
"Tm30 Shadow Ball",
"Tm31 Brick Break",
"Tm32 Double Team",
"Tm33 Reflect",
"Tm34 Shock Wave",
"Tm35 Flamethrower",
"Tm36 Sludge Bomb",
"Tm37 Sandstorm",
"Tm38 Fire Blast",
"Tm39 Rock Tomb",
"Tm40 Aerial Ace",
"Tm41 Torment",
"Tm42 Facade",
"Tm43 Secret Power",
"Tm44 Rest",
"Tm45 Attract",
"Tm46 Thief",
"Tm47 Steel Wing",
"Tm48 Skill Swap",
"Tm49 Snatch",
"Tm50 Overheat",
"Hm01 Cut",
"Hm02 Fly",
"Hm03 Surf",
"Hm04 Strength",
"Hm05 Flash",
"Hm06 Rock Smash",
"Hm07 Waterfall",
"Hm08 Dive",
"15b",
"15c",
"Oaks Parcel",
"Poke Flute",
"Secret Key",
"Bike Voucher",
"Gold Teeth",
"Old Amber",
"Card Key",
"Lift Key",
"Helix Fossil",
"Dome Fossil",
"Silph Scope",
"Bicycle",
"Town Map",
"Vs Seeker",
"Fame Checker",
"Tm Case",
"Berry Pouch",
"Teachy Tv",
"Tri Pass",
"Rainbow Pass",
"Tea",
"Mystic Ticket",
"Aurora Ticket",
"Powder Jar",
"Ruby",
};
#endif
