#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 06 13:46:20 CET 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TradeHandler_tb_behav -key {Behavioral:sim_1:Functional:TradeHandler_tb} -tclbatch TradeHandler_tb.tcl -protoinst "protoinst_files/bd_5375.protoinst" -protoinst "protoinst_files/GB_UNIT_design.protoinst" -view /home/daniel/Masterthesis/GB_MASTER_UNIT/TradeHandler_tb_behav.wcfg -log simulate.log"
xsim TradeHandler_tb_behav -key {Behavioral:sim_1:Functional:TradeHandler_tb} -tclbatch TradeHandler_tb.tcl -protoinst "protoinst_files/bd_5375.protoinst" -protoinst "protoinst_files/GB_UNIT_design.protoinst" -view /home/daniel/Masterthesis/GB_MASTER_UNIT/TradeHandler_tb_behav.wcfg -log simulate.log

