#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 22 23:28:00 CET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim TopModule_TB_behav -key {Behavioral:sim_1:Functional:TopModule_TB} -tclbatch TopModule_TB.tcl -protoinst "protoinst_files/GB_UNIT_design.protoinst" -view /home/daniel/Masterthesis/GB_MASTER_UNIT/TopModule_TB_behav.wcfg -log simulate.log"
xsim TopModule_TB_behav -key {Behavioral:sim_1:Functional:TopModule_TB} -tclbatch TopModule_TB.tcl -protoinst "protoinst_files/GB_UNIT_design.protoinst" -view /home/daniel/Masterthesis/GB_MASTER_UNIT/TopModule_TB_behav.wcfg -log simulate.log

