#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Mar 16 19:04:18 CET 2024
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Ringbuffer_tb_behav -key {Behavioral:sim_1:Functional:Ringbuffer_tb} -tclbatch Ringbuffer_tb.tcl -protoinst "protoinst_files/bd_5375.protoinst" -protoinst "protoinst_files/GB_UNIT_design.protoinst" -view /home/daniel/Masterthesis/GB_MASTER_UNIT/Ringbuffer_tb_behav.wcfg -view /home/daniel/Masterthesis/GB_MASTER_UNIT/TradeHandler_tb_behav.wcfg -view /home/daniel/Masterthesis/GB_MASTER_UNIT/FrameCounterGenerator_TB_behav.wcfg -log simulate.log"
xsim Ringbuffer_tb_behav -key {Behavioral:sim_1:Functional:Ringbuffer_tb} -tclbatch Ringbuffer_tb.tcl -protoinst "protoinst_files/bd_5375.protoinst" -protoinst "protoinst_files/GB_UNIT_design.protoinst" -view /home/daniel/Masterthesis/GB_MASTER_UNIT/Ringbuffer_tb_behav.wcfg -view /home/daniel/Masterthesis/GB_MASTER_UNIT/TradeHandler_tb_behav.wcfg -view /home/daniel/Masterthesis/GB_MASTER_UNIT/FrameCounterGenerator_TB_behav.wcfg -log simulate.log

