#include "MainCHeader.h"

const float NatureModifierTable[NUM_NATURES][NUM_NATURE_STATS] =
{                      // Attack  Defense  Speed  Sp.Atk  Sp.Def
    [NATURE_HARDY]   = {    1,      1,      1,      1,      1   },
    [NATURE_LONELY]  = {   1.1,     0.9,      1,      1,      1   },
    [NATURE_BRAVE]   = {   1.1,      1,     0.9,      1,      1   },
    [NATURE_ADAMANT] = {   1.1,      1,      1,     0.9,      1   },
    [NATURE_NAUGHTY] = {   1.1,      1,      1,      1,     0.9   },
    [NATURE_BOLD]    = {   0.9,     1.1,      1,      1,      1   },
    [NATURE_DOCILE]  = {    1,      1,      1,      1,      1   },
    [NATURE_RELAXED] = {    1,     1.1,     0.9,      1,      1   },
    [NATURE_IMPISH]  = {    1,     1.1,      1,     0.9,      1   },
    [NATURE_LAX]     = {    1,     1.1,      1,      1,     0.9   },
    [NATURE_TIMID]   = {   0.9,      1,     1.1,      1,      1   },
    [NATURE_HASTY]   = {    1,     0.9,     1.1,      1,      1   },
    [NATURE_SERIOUS] = {    1,      1,      1,      1,      1   },
    [NATURE_JOLLY]   = {    1,      1,     1.1,     0.9,      1   },
    [NATURE_NAIVE]   = {    1,      1,     1.1,      1,     0.9   },
    [NATURE_MODEST]  = {   0.9,      1,      1,     1.1,      1   },
    [NATURE_MILD]    = {    1,     0.9,      1,     1.1,      1   },
    [NATURE_QUIET]   = {    1,      1,     0.9,     1.1,      1   },
    [NATURE_BASHFUL] = {    1,      1,      1,      1,      1   },
    [NATURE_RASH]    = {    1,      1,      1,     1.1,     0.9   },
    [NATURE_CALM]    = {   0.9,      1,      1,      1,     1.1   },
    [NATURE_GENTLE]  = {    1,     0.9,      1,      1,     1.1   },
    [NATURE_SASSY]   = {    1,      1,     0.9,      1,     1.1   },
    [NATURE_CAREFUL] = {    1,      1,      1,     0.9,     1.1   },
    [NATURE_QUIRKY]  = {    1,      1,      1,      1,      1   },
};

char nature_string[][20]={
        "Hardy",
        "Lonely",
        "Brave",
        "Adamant",
        "Naughty",
        "Bold",
        "Docile",
        "Relaxed",
        "Impish",
        "Lax",
        "Timid",
        "Hasty",
        "Serious",
        "Jolly",
        "Naive",
        "Modest",
        "Mild",
        "Quiet",
        "Bashful",
        "Rash",
        "Calm",
        "Gentle",
        "Sassy",
        "Careful",
        "Quirky"
};