

#define SPECIES SPECIES_BULBASAUR
#define ITEM_INDEX ITEM_RARE_CANDY
#define EXPERIENCE 1250000
#define MOVE1_INDEX MOVE_HIDDEN_POWER
#define MOVE2_INDEX MOVE_NONE
#define MOVE3_INDEX MOVE_NONE
#define MOVE4_INDEX MOVE_NONE

#define HP_EV 0
#define ATTACK_EV 0
#define DEFENSE_EV 0
#define SPEED_EV 0
#define SPEZ_ATTACK_EV 0
#define SPEZ_DEFENSE_EV 0

#define HP_IV 31
#define ATTACK_IV 31
#define DEFENSE_IV 31
#define SPEED_IV 31
#define SPEZ_ATTACK_IV 31
#define SPEZ_DEFENSE_IV 31



#define MET_GAME GAME_LEAFGREEN
#define POKEBALL_CAUGHT POKEBALL_STANDARD
#define MET_LANGUAGE LANGUAGE_GERMAN
#define MET_LEVEL 0
#define MET_LOCATION 0x58
#define LEVEL 100


#define NATURE 0

#define SECRET_ID_LAMBO 0x06A6
#define SECRET_ID_KEVIN 0x392B

#define TRAINER_ID_LAMBO 0x4753
#define TRAINER_ID_KEVIN 0x8D44

#define SECRET_ID_DANIEL 0x60AC
#define OT_TRAINER_ID_DANIEL 0xC371
#define TRAINER_ID_DANIEL 0x60ACC371 //Leafgreen Daniel

#define SECRET_ID SECRET_ID_DANIEL
#define OT_TRAINER_ID OT_TRAINER_ID_DANIEL
//#define TRAINER_ID 0x06A64753

//#define TRAINER_ID 0x60ACC371 //Leafgreen Daniel
#define TRAINER_ID (SECRET_ID << 16) + OT_TRAINER_ID

  char nickname[NICKNAME_LENGTH] = "Pokemon";
  char trainer_name[TRAINER_NAME_LENGTH] = "Daniel";
